Title : AirAlert

left to right direction
skinparam style strictuml
skinparam packageStyle rect

actor Utilisateur as user
rectangle "Serveur" {
    rectangle "Site" {
        (Se connecter) as connect
        user --> connect
        (Se déconnecter) as disconnect
        disconnect ..> connect : <<include>>
        user --> disconnect
        (S'abbonner à un flux) as aboFlux
        connect <.. aboFlux : << include >>
        (Se désabonner à un flux) as daboFlux
        connect <.. daboFlux : << include >>
        aboFlux <.. daboFlux : << include >>
        user --> aboFlux
        user --> daboFlux
        (Consulter les données) as checkData
        user --> checkData
        checkData ..> connect : <<include>>
        checkData ..> aboFlux : <<include>>
    } 
    (Envoyer les données) as sendData
}
actor Station 
Station --> sendData
